In [1]:
import pandas as pd
import numpy as np

file_paths = ('Resources/Airbnb_Spring_listings.csv.gz')

def clean_df(file_path):

    # read csv to dataframe

    full_df = pd.read_csv(file_path, compression='gzip')

    # select columns we're interested in for ml model and dashboard

    analysis_df = full_df[["price","neighbourhood_cleansed","room_type","accommodates","longitude","latitude","beds","bedrooms",

        "property_type","bathrooms_text","review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness", 

        "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value", "license", "host_name"]]

    # process NaNs

    # drop nan beds and bathrooms_text

    analysis_df.dropna(subset = ['beds', 'bathrooms_text'], inplace = True)


    # replace NaNs with values based on columns.  Average ratings for review_scores to 2 dec places,

    # text for host_name and license

    values = {"host_name":"No Host Listed", 

              "review_scores_rating": round(analysis_df['review_scores_rating'].mean(), 2), 

              "review_scores_accuracy": round(analysis_df['review_scores_accuracy'].mean(), 2),

              "review_scores_cleanliness": round(analysis_df['review_scores_cleanliness'].mean(), 2),

              "review_scores_checkin": round(analysis_df['review_scores_checkin'].mean(), 2),

              "review_scores_communication": round(analysis_df['review_scores_communication'].mean(), 2),

              "review_scores_location": round(analysis_df['review_scores_location'].mean(), 2),

              "review_scores_value": round(analysis_df['review_scores_value'].mean(), 2),

              "bedrooms": analysis_df.loc[full_df['bedrooms'].isna()]['beds'],

              "license": "No License"}

    analysis_df = analysis_df.fillna(value = values)


    # convert price to float

    analysis_df['price'] = analysis_df['price'].str.replace('$', '')

    analysis_df['price'] = analysis_df['price'].str.replace(',', '').astype(float)


    # convert bathrooms_text to float

    analysis_df['bathrooms_text'] = analysis_df['bathrooms_text'].str.split(n=1, expand=True)[0]

    # all bathroom_text values without a number are half baths, verified with value_counts() function

    # all text values contain the letter a, other values are purely numeric at this point

    analysis_df.loc[analysis_df['bathrooms_text'].str.contains('a'), 'bathrooms_text'] = 0.5


    # rename bathrooms_text as bathrooms

    analysis_df['bathrooms'] = analysis_df['bathrooms_text'].astype(float)

    analysis_df.drop(['bathrooms_text'], axis = 1, inplace = True)


    return analysis_df

In [2]:
df= clean_df(file_paths)

<ipython-input-1-6068ea200cfa>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analysis_df.dropna(subset = ['beds', 'bathrooms_text'], inplace = True)

In [3]:
df

,price,neighbourhood_cleansed,room_type,accommodates,longitude,latitude,beds,bedrooms,property_type,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,host_name,bathrooms
0,60.0,Egger Highlands,Private room,2,-117.117550,32.588800,1.0,1.0,Private room in rental unit,5.00,5.00,5.00,5.00,5.00,4.00,5.00,No License,Teresa,1.0
1,282.0,Del Mar Heights,Entire home/apt,6,-117.256290,32.983710,3.0,3.0,Entire residential home,4.87,4.91,4.64,4.99,4.98,4.87,4.86,No License,Craig,2.5
2,348.0,Del Mar Heights,Entire home/apt,2,-117.256960,32.985420,1.0,1.0,Entire residential home,4.92,5.00,4.92,5.00,5.00,4.92,4.92,No License,Logan,1.0
3,368.0,Del Mar Heights,Entire home/apt,6,-117.259830,32.982320,4.0,3.0,Entire townhouse,4.88,4.96,4.96,5.00,5.00,4.75,4.71,No License,Brenda,2.5
4,264.0,Del Mar Heights,Entire home/apt,4,-117.258310,32.980600,1.0,1.0,Entire serviced apartment,5.00,5.00,4.75,4.75,4.75,5.00,4.75,No License,Kim And Hamid,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10930,228.0,Darnall,Entire home/apt,8,-117.048090,32.752850,7.0,3.0,Entire residential home,4.78,4.82,4.85,4.98,4.90,4.82,4.80,No License,Pete And Tess,1.0
10931,168.0,Tijuana River Valley,Entire home/apt,8,-117.118988,32.531868,3.0,3.0,Entire condominium (condo),4.89,4.94,4.89,4.93,4.94,4.92,4.90,No License,Jose Luis,3.0
10932,500.0,Midtown District,Entire home/apt,2,-117.220780,32.759110,1.0,1.0,Entire cottage,5.00,4.50,5.00,5.00,5.00,5.00,5.00,No License,Georgia,1.0
10933,67.0,San Ysidro,Entire home/apt,4,-117.031220,32.540710,2.0,2.0,Entire rental unit,4.53,4.82,4.67,4.67,4.69,4.71,4.61,No License,Tj Border Suites,1.0
10934,88.0,Ocean Beach,Entire home/apt,2,-117.252230,32.754530,1.0,1.0,Entire condominium (condo),4.54,4.77,4.77,4.89,4.80,4.83,4.56,No License,Natalia,1.0

In [5]:
df.to_csv(r'C:\Users\vishm\Desktop\export_dataframe.csv',index = False, header=True)